name: fe
description: "Banking Mobile project"

publish_to: 'none' # Private package, not published to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0" # Đảm bảo sử dụng Dart SDK tương thích với null safety

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5 # Để mở URL thanh toán




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Đảm bảo các quy tắc mới nhất

flutter:
  uses-material-design: true

  assets:
    - lib/images/
